### ISSUE TITLE
LinuxParser.Kernel does not return correct string

### ISSUE THREAD

**Issue by djhanove** [udacity/CppND-System-Monitor-Project-Updated#12]
Function needs to be updated so that it returns the proper value of the linux kernel defined in /proc/version. As it stands, right now the function returns the string "version" instead of string directly after version. All images used in the C++ course showing the htop display have the kernel field showing "version" instead of the proper value. 

I'm more than happy to fix this, just give me a shout.

**Comment by SudKul** [comment]
Hi @djhanove 
Thanks for flagging the issue. Can you raise a PR, so that we can review it precisely?

**Comment by djhanove** [comment]
I don't have the bandwidth for this currently, and opened this issue almost a year ago. Not sure why you are closing the issue unless it has been patched by someone else

**Comment by SudKul** [comment]
We've got that. See [this commit](https://github.com/udacity/CppND-System-Monitor-Project-Updated/commit/916dd64116b35b94ccebea3cdf1dadb56d2a4114). It has now been resolved.
