### ISSUE TITLE
ncurses_display processes list - out of range if process list is short

### ISSUE THREAD

**Issue by psnx** [udacity/CppND-System-Monitor-Project-Updated#15]
Ref
https://github.com/udacity/CppND-System-Monitor-Project-Updated/blob/86b73a9f5675fc584469f3df3b884d5c6123a609/src/ncurses_display.cpp#L72

If the size of the `processes` list is less than `n`, the loop goes out of range and picks up some random gibberish.  
I propose that the line be changed to check the list's size:  
```cpp
for (int i = 0; i < n && i < (int)processes.size(); ++i)
```
Similarly when the `processes` list shrinks the number of rows do not shrink accordingly. I propose something like that at the end of the function:
```cpp
 // filling rows with white space after deleted processes
  for (int i = (int)processes.size(); i < n; ++i) {
    mvwprintw(window, ++row, pid_column,
              "                                                                                                 ");
  }
```

**Comment by SudKul** [comment]
Hi @psnx 
This issue has now been fixed in https://github.com/udacity/CppND-System-Monitor-Project-Updated/pull/13 
Thank you.
