### ISSUE TITLE
RAM calculation

### ISSUE THREAD

**Issue by nikolim** [udacity/CppND-System-Monitor-Project-Updated#21]
Hello I am working on the project right now and I think the calculation of the RAM is not quite correct. Also on the example screenshot the Firefox process has 34390 MB = 34 GB alone.

**Comment by the-rab-bit** [comment]
Hello nikolim, as far as I can see, regarding project instructions we are told to take the value of the virtual memory (VSZ). Regarding this [StackOverflow answer](https://stackoverflow.com/a/21049737), explaining the differences between VSZ and resident set size(RSS), it is always bigger than RSS. So your measurement with Firefox becomes quite realistic. htop displays the VSZ value as VIRT, the RSS value as RES.

**Comment by SudKul** [comment]
Hello @nikolim 
Marking this issue as closed. 
Feel free to discuss on the Knowledge thread so that Udacity mentors can respond to your concerns, and new students can also benefit from the thread (even if it is closed). 
Thank you.
