### ISSUE TITLE
Add -Wall and error flags to CMakeLists.txt

### ISSUE THREAD

**Issue by dsilver829** [udacity/CppND-System-Monitor-Project-Updated#7]
We should give students scaffolding that compiles without error.

**Comment by SudKul** [comment]
Hi @dsilver829 
Looks like you've raised a few issues to keep track, before making commits to the current repo (in Jul 2019).
We are trying to clean our repos, by fixing issues and PRs, if any. 

Thanks, for all the wonderful contributions.
